### ISSUE TITLE
如何对接入参是cvmat的函数

### ISSUE THREAD

**Issue by yueyue0574** [PaddlePaddle/FlyCV#107]
项目中很多函数，包括第三方接口，入参需求是cvmat，我用flycv拿到的是fcvmat，该如何处理呢

**Comment by ChaoII** [comment]
可以暂时参考这里面的实现https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/common/processors/utils.cc

**Comment by yueyue0574** [comment]
> 可以暂时参考这里面的实现https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/common/processors/utils.cc

感谢
