### ISSUE TITLE
怎么感觉在arm上加速不是很明显

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/FlyCV#11]
下图是和opencv的resize接口耗时对比
![image](https://user-images.githubusercontent.com/48303408/203280951-c26fa6f6-4a99-47b9-abbb-668c3c334715.png)

用的开发板如下
![image](https://user-images.githubusercontent.com/48303408/203281248-4e791277-1c74-409c-8e66-84363e609e76.png)

**Comment by TomasRan** [comment]
请问初始和结果的分辨率分别是多少，以及使用的插值方式

**Comment by Dandelion111** [comment]
> 请问初始和结果的分辨率分别是多少，以及使用的插值方式

右1280×960缩放到192×192，插值方式就是默认的，应该是INTER_LINEAR

**Comment by litonghui** [comment]
@Dandelion111  确认一下，你在测试时候，openCV 的getNumThreads() 和 flycv的get_thread_num（） 打印分别是多少，如果不一样，可以通过openCV 的setNumThreads（） 和  flycv set_thread_num（） 设置相同测试。我们根据你的case 1280×960缩放到192×192 双线性插值，在benchmark 测试，性能还是有明显差异。
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7567562/203491749-eacb8e9a-68c5-41f3-bbd8-c3965bd88d7b.png">

**Comment by Dandelion111** [comment]
> @Dandelion111 确认一下，你在测试时候，openCV 的getNumThreads() 和 flycv的get_thread_num（） 打印分别是多少，如果不一样，可以通过openCV 的setNumThreads（） 和 flycv set_thread_num（） 设置相同测试。我们根据你的case 1280×960缩放到192×192 双线性插值，在benchmark 测试，性能还是有明显差异。 <img alt="image" width="791" src="https://user-images.githubusercontent.com/7567562/203491749-eacb8e9a-68c5-41f3-bbd8-c3965bd88d7b.png">

好的谢谢大佬回复

**Comment by Dandelion111** [comment]
> @Dandelion111 确认一下，你在测试时候，openCV 的getNumThreads() 和 flycv的get_thread_num（） 打印分别是多少，如果不一样，可以通过openCV 的setNumThreads（） 和 flycv set_thread_num（） 设置相同测试。我们根据你的case 1280×960缩放到192×192 双线性插值，在benchmark 测试，性能还是有明显差异。 <img alt="image" width="791" src="https://user-images.githubusercontent.com/7567562/203491749-eacb8e9a-68c5-41f3-bbd8-c3965bd88d7b.png">

大佬你好，我在cv::resize和fcv::resize接口前面分别加了打印线程数，结果：
![7894eefdd466a65b4dad3b5ce23c459](https://user-images.githubusercontent.com/48303408/203779722-aeae1a5d-e82f-4cfa-b22a-7ead32fae989.jpg)
fcv是2个线程，cv是1个线程

**Comment by TomasRan** [comment]
方便贴一下测评的代码么？包含线程设置和耗时统计的部分。

**Comment by Dandelion111** [comment]
> 方便贴一下测评的代码么？包含线程设置和耗时统计的部分。

![image](https://user-images.githubusercontent.com/48303408/203889495-d608e5c0-b833-4ea9-8b6e-901f94192f16.png)

**Comment by TomasRan** [comment]
> 

在flycv resize调用之前，也设置线程数为1，看看耗时结果：fcv::set_thread_num(1)

**Comment by TomasRan** [comment]
另外代码中的fcv_image_size和image_resize是否都未分配内存，以及你这个是只跑了一次没有循环是么？

**Comment by Dandelion111** [comment]
> > 
> 
> 在flycv resize调用之前，也设置线程数为1，看看耗时结果：fcv::set_thread_num(1)

都设置为1个线程的时候，确实比opencv快了一点
![image](https://user-images.githubusercontent.com/48303408/203929344-3fb2b7ff-2b00-4db7-938f-9753407b6eac.png)

**Comment by Dandelion111** [comment]
> 另外代码中的fcv_image_size和image_resize是否都未分配内存，以及你这个是只跑了一次没有循环是么？

都未分配内存，每次耗时打印确实只跑一张图，但我观察了很多张图，结果是差不多的

**Comment by TomasRan** [comment]
板子是armlinux系统？

**Comment by Dandelion111** [comment]
> 板子是armlinux系统？

是armlinux的，我推理模型的时候如果设置NO_BIND模式的话，设置2个线程耗时会暴增，不知道是不是板子的问题

**Comment by TomasRan** [comment]
> > 板子是armlinux系统？
> 
> 是armlinux的，我用paddlelite推理模型的时候如果设置NO_BIND模式的话，设置2个线程耗时会暴增，不知道是不是板子的问题

嗯，armlinux的开发板环境差别可能稍微大点，目前评测了8+机型性能收益还都比较明显，后续再重点关注下不同armlinux开发板。

**Comment by Dandelion111** [comment]
> > > 板子是armlinux系统？
> > 
> > 
> > 是armlinux的，我用paddlelite推理模型的时候如果设置NO_BIND模式的话，设置2个线程耗时会暴增，不知道是不是板子的问题
> 
> 嗯，armlinux的开发板环境差别可能稍微大点，目前评测了8+机型性能收益还都比较明显，后续再重点关注下不同armlinux开发板。

好的，谢谢大佬
