### ISSUE TITLE
fcv::crop函数

### ISSUE THREAD

**Issue by fengyanWang** [PaddlePaddle/FlyCV#121]
- lycv版本：flycv-v1.0.0-android.tar
- 平台：展锐T610 CPU armv7
- 复现步骤：读取本地图片，然后在A函数中调用fcv::crop函数，最后在B函数中调用A函数，编译可以过，但是链接出错

#include "flycv.h"

void A(fcv::Mat& src_img,fcv::Mat& dst_img){
    fcv::crop(src_img, dst_img, fcv::RectI(0,0,100,100));
}
int main(){
   std::string raw_img_path = "/sdcard/Android/data/com.baidu.paddle.lite.demo.ssd_detection/cache/raw.jpg";
  fcv::Mat raw_img = fcv::imread(raw_img_path);
  
  fsv::dst_img;
  A(raw_img,dst_img);

}

- 现象：注释掉A函数中的fcv::crop，能够成功编译运行或者在main函数中不调用也能成功编译运行
- 输出错误信息：
error: undefined reference to 'fcv::crop(fcv::Mat&, fcv::Mat&, fcv::Rect_<int>)'

**Comment by VoidSalts** [comment]
可以尝试将
`fcv::crop(src_img, dst_img, fcv::RectI(0,0,100,100));`
改为
`fcv::Rect roi = fcv::Rect(0, 0, 100, 100);
fcv::crop(src_img, dst_img, roi);`
试下
（另外也可以查验下编译时链接文件libflycv_shared.so/.a的路径）

**Comment by fengyanWang** [comment]
> 可以尝试将 `fcv::crop(src_img, dst_img, fcv::RectI(0,0,100,100));` 改为 `fcv::Rect roi = fcv::Rect(0, 0, 100, 100); fcv::crop(src_img, dst_img, roi);` 试下 （另外也可以查验下编译时链接文件libflycv_shared.so/.a的路径）

第一种方法试了，还是一样的错误
第二种情况基本可以排除，因为fcv中其它的函数可以正常使用，如果是路径问题，不应该只有这个函数报错

**Comment by VoidSalts** [comment]
方便查看下编译时这个API头文件（flycv/include/modules/img_transform/crop/interface/crop.h）的API声明么？
这个报错符号确实没有'fcv::crop(fcv::Mat&, fcv::Mat&, fcv::Rect_)'，第三个参数应该是传引用不是报错中的值传递
实际应该是这个'fcv::crop(fcv::Mat&, fcv::Mat&, fcv::Rect_&)'

**Comment by fengyanWang** [comment]
> 方便查看下编译时这个API头文件（flycv/include/modules/img_transform/crop/interface/crop.h）的API声明么？ 这个报错符号确实没有'fcv::crop(fcv::Mat&, fcv::Mat&, fcv::Rect_)'，第三个参数应该是传引用不是报错中的值传递 实际应该是这个'fcv::crop(fcv::Mat&, fcv::Mat&, fcv::Rect_&)'

头文件中crop函数申明：FCV_API int crop(Mat& src, Mat& dst, Rect_<int> drect);
针对Rext类中，有 typedef Rect_<int> RectI;

所以应该没有传错吧

**Comment by VoidSalts** [comment]
那方便把头文件中接口声明中的Rect_更正为Rect&，然后编译试下么
（PS：我这边下载了https://github.com/PaddlePaddle/FlyCV/releases 这个预编译库，看里面的声明也是引用，可能是不小心误删了个&符号吧）

**Comment by fengyanWang** [comment]
> 然后
谢谢哈！修改头文件申明后，编译链接没问题了，修改后申明如下：

FCV_API int crop(Mat& src, Mat& dst, Rect& drect);
