### ISSUE TITLE
flycv 支持 vs插件ImageWatch吗?

### ISSUE THREAD

**Issue by gaojunling** [PaddlePaddle/FlyCV#19]
请问flycv 支持 vs插件ImageWatch吗,能支持这个很重要,调试方便? 或者,opencv 的mat 可以和flycv的mat互相转换也行.

**Comment by TomasRan** [comment]
ImageWatch目前未支持。opencv mat和flycv mat相互转换需要同时依赖这两个库，未来我们可以提供一个上层封装的接口支持转换。
