### ISSUE TITLE
CVT_PA_BGR2PA_RGB不生效

### ISSUE THREAD

**Issue by stefan252423** [PaddlePaddle/FlyCV#205]
测试代码段
    fcv::Mat dst;
    fcv::Mat src = fcv::imread("user.jpg");
    for (int i = 0; i < 20; ++i)
    {
        unsigned char* p = (unsigned char*)src.data();
        int a = p[i];
        std::cout << a << " ";
    }
    std::cout << std::endl;
    std::cout << "****" <<std::endl;
    fcv::cvt_color(src, src, fcv::ColorConvertType::CVT_PA_BGR2PA_RGB);
    for (int i = 0; i < 20; ++i)
    {
        unsigned char* p = (unsigned char*)src.data();
        int a = p[i];
        std::cout << a << " ";
    }

输出结果：
65 71 48 66 72 49 66 71 50 65 70 49 64 69 48 67 72 51 70 76 
****
65 71 48 66 72 49 66 71 50 65 70 49 64 69 48 67 72 51 70 76

**Comment by ndghw** [comment]
我这个BGR转RGB时，出来的结果64位的andorid系统正常，32位的左半边是正常，右半边被填充为全0了，希望官方能帮忙看看

**Comment by ndghw** [comment]
补充一下：是32位的包跑在64位的机器上

**Comment by stefan252423** [comment]
> 测试代码段 fcv::Mat dst; fcv::Mat src = fcv::imread("user.jpg"); for (int i = 0; i < 20; ++i) { unsigned char* p = (unsigned char*)src.data(); int a = p[i]; std::cout << a << " "; } std::cout << std::endl; std::cout << "**__" <<std::endl; fcv::cvt_color(src, src, fcv::ColorConvertType::CVT_PA_BGR2PA_RGB); for (int i = 0; i < 20; ++i) { unsigned char_ p = (unsigned char_)src.data(); int a = p[i]; std::cout << a << " "; }
> 
> 输出结果： 65 71 48 66 72 49 66 71 50 65 70 49 64 69 48 67 72 51 70 76
> 
> 65 71 48 66 72 49 66 71 50 65 70 49 64 69 48 67 72 51 70 76

这种写法正确:
 fcv::Mat dst;
 fcv::cvt_color(src, dst, fcv::ColorConvertType::CVT_PA_BGR2PA_RGB);
src和dst不可以是同一个Mat，必须重新定义新的Mat
