### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by huyuejingling** [PaddlePaddle/FlyCV#4]
windows 目前只有支持vs 2015吗？

**Comment by TomasRan** [comment]
理论都支持，请问你是用哪个版本VS编译失败

**Comment by TomasRan** [comment]
已修复，原因是msvc不支持该类型，gcc编译器可以支持。

**Comment by TomasRan** [comment]
是否还有问题？如果没有这个issue就关闭了

**Comment by huyuejingling** [comment]
windows下我已经编译通过了并测试成功了，但Linux下我编译了一下，找不到 -lpthreads，我升级了gcc 到11，使用了devtoolset,也没有能解决

**Comment by TomasRan** [comment]
请问你使用的linux系统具体是哪个版本？

**Comment by huyuejingling** [comment]
centos 7

**Comment by TomasRan** [comment]
执行的脚本是scripts/linux下的脚本么，以及linux下的编译失败日志可以贴一下？

**Comment by huyuejingling** [comment]
![image](https://user-images.githubusercontent.com/7887096/203195766-1277167a-4463-42fe-925a-89d6cc29540a.png)
![image](https://user-images.githubusercontent.com/7887096/203195821-dd535996-7c4a-4503-8103-cfa491f15f51.png)

**Comment by TomasRan** [comment]
看日志编译错误是上层写的demo引发的，flycv单独编译是否已通过？另外linux端使用pthread.h gcc编译参数应该是-pthread

**Comment by TomasRan** [comment]
好的，那看上去flycv是能够成功编译，上面的编译错误应该跟flycv无关。
