### ISSUE TITLE
windows编译必须先编译静态库才能编译动态库

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/FlyCV#89]
如果先编译动态库：
```
mkdir build
cd build
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./Release -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=OFF -DWITH_LIB_PNG=ON -DWITH_LIB_JPEG_TURBO=ON -DBUILD_C=ON
ninja all
```

则会报如下错：
```
C:\_\code\FlyCV\build>ninja all
ninja: error: 'third_party/libjpeg-turbo/output/lib/turbojpeg-static.lib', needed by 'modules/flycv_shared.dll', missing and no known rule to make it
```

必须先编译静态库：
```
C:\_\code\FlyCV\build>cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=OFF -DWITH_LIB_PNG=ON -DWITH_LIB_JPEG_TURBO=ON -DBUILD_C=ON
ninja all
```

静态库编译成功之后，才能正常编译动态库。

**Comment by VoidSalts** [comment]
方便问下，您这边用的编译器是？
我这边用了类似的命令生成VS2022工程，用msbuild编译可以通过
` cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./Release -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=OFF -DWITH_LIB_PNG=ON -DWITH_LIB_JPEG_TURBO=ON -DBUILD_C=ON ..
 MSBuild.exe flycv.sln /property:Configuration=Release
`

**Comment by sdcb** [comment]
我这边也是VS 2022社区版，但我用的是ninja，不确认这是否与ninja有关。

**Comment by VoidSalts** [comment]
使用ninja的话，这样应该可以：
`ninja libjpeg-turbo`
`ninja libpng`
`ninja all`

**Comment by sdcb** [comment]
感谢大佬，我重新测试了一下，`ninja all`之前，还需要`ninja libjpeg-turbo`, `ninja zlib`, `ninja libpng`三个东西，有了这3个再`ninja all`就确实成功了。

但是大佬，这个按道理应该修复的，希望修复一下吧。

**Comment by VoidSalts** [comment]
目前最新的develop分支已修复这个问题（ 71a92a42），ninja all目前可以正常运转了，有需要的话可以更新验证下

**Comment by sdcb** [comment]
确认使用最新版本ninja all可以正常编译动态库了，感谢！
